SAM2_CHECKPOINT = "external/sam2/checkpoints/sam2.1_hiera_large.pt"
SAM2_MODEL_CONFIG = "configs/sam2.1/sam2.1_hiera_l.yaml"


DATA_FOLDER = "data"


MEDIA_FOLDER = f"{DATA_FOLDER}/media"

ALIGNMENT_MEDIA_FOLDER = f"{MEDIA_FOLDER}/alignment"
CROPS_FOLDER = f"{MEDIA_FOLDER}/crops"
FRAMES_FOLDER = f"{MEDIA_FOLDER}/frames"
MASKED_CROPS_FOLDER = f"{MEDIA_FOLDER}/masked_crops"
VIDEOS_FOLDER = f"{MEDIA_FOLDER}/videos"
VISUALIZATIONS_FOLDER = f"{MEDIA_FOLDER}/visualizations"


METADATA_FOLDER = f"{DATA_FOLDER}/metadata"

ALIGNMENT_METADATA_FOLDER = f"{METADATA_FOLDER}/alignment"
ANNOTATIONS_FOLDER = f"{METADATA_FOLDER}/annotations"
TRACKS_FOLDER = f"{METADATA_FOLDER}/tracks"


REVIEWS_FOLDER = "reviews"
